### ISSUE TITLE
Create Basic Project Structure & Auth

### ISSUE THREAD

**Issue by Valx01P** [web103-group6/web103_team6_final_project#1]
### Issue Title: Create Basic Project Structure + Auth

---

**Description**  
- Migrate the authentication system of the entire app to use **Supabase Auth**.
- This is crucial to streamline authentication, improve security, and leverage Supabase’s built-in authentication features.

---

**Task List**  
- [x] Step 1: Create the basic backend layout
- [x] Step 2: Create the data models to be used
- [x] Step 3: Create the basic frontend layout
- [x] Step 4: Develop the starting auth (app signup and github oauth)
- [x] Step 5: Ensure these changes work

---

**Acceptance Criteria**  
- [x] The auth works, nothing breaks
---

**Branch Navigation**  
git fetch origin

---

**Resources / References**  
- [Figma/design link](https://www.figma.com/design/xmnSKIwNRpxlfmQto7CzPW/WEB103-Wireframe-Idea?node-id=0-1&t=0rCyNGm7K5iVk0MS-1)  
- [Project Overview](https://docs.google.com/presentation/d/1iKk3Y5fWfzqOxhCgJuhghPjHF2_B1LICL6oA_TiC16s/edit#slide=id.g303602671a0_0_362)  

---

**Assignee(s)**  
- @Valx01P
