### ISSUE TITLE
Develop User Routes & Controller Logic

### ISSUE THREAD

**Issue by Valx01P** [web103-group6/web103_team6_final_project#3]
### Issue Title: Develop User Routes & Controller Logic
---

**Description**  
- Develop all required User routes with their respective controller logic for the project
---

**Task List**  
- [ ] Step 1: Figure out what routes are necessary based on the project and data relations
- [ ] Step 2: Implement them

---

**Acceptance Criteria**  
- [ ] The user routes and controller logic work
---
**Assignee(s)**  
- @Valx01P
