### ISSUE TITLE
Develop Post Routes & Controller Logic

### ISSUE THREAD

**Issue by Valx01P** [web103-group6/web103_team6_final_project#4]
### Issue Title: Develop Post Routes & Controller Logic
---

**Description**  
- Add routes and controller logic for 'posts' as modeled in our initDB file, ensure the structure of the posts made follow our database model, make sure only users that own a post can delete or edit it.
 
---

**Task List**  
- [ ] Step 1: Make a way to get posts
- [ ] Step 2: Make a way to edit your own post
- [ ] Step 3: Make a way to delete your own post
- [ ] Step 4: Make a way to get a specific post
- [ ] Step 5: Make a way to create new posts

---

**Acceptance Criteria**  
- [ ] Completing or exceeding required task list
---

**Branch Navigation**  
git fetch origin
git checkout posts

---

**Resources / References**  
- [Figma/design link](https://www.figma.com/design/xmnSKIwNRpxlfmQto7CzPW/WEB103-Wireframe-Idea?node-id=0-1&t=0rCyNGm7K5iVk0MS-1)  
- [Project Powerpoint](https://docs.google.com/presentation/d/1iKk3Y5fWfzqOxhCgJuhghPjHF2_B1LICL6oA_TiC16s/edit#slide=id.g303602671a0_0_362)  

---

**Assignee(s)**  
- @VicAlexSim
